apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB}
    user: ${INFLUXDB_ADMIN_USER}
    secureJsonData:
      password: ${INFLUXDB_ADMIN_PASSWORD}
    jsonData:
      httpMode: POST
      version: InfluxQL
    isDefault: true
    editable: true
