apiVersion: 1

datasources:
  - name: InfluxDB_v1
    uid: InfluxDB_v1
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: $INFLUXDB_ADMIN_USER
    secureJsonData:
      password: $INFLUXDB_ADMIN_PASSWORD
    jsonData:
      version: InfluxQL
      dbName: $INFLUXDB_DB
      httpMode: POST
    isDefault: true
    editable: true
